postgres_db:
  host: "127.0.0.1"
  port: 5432
  user: "auth_admin"
  password: "password123"
  db_name: "auth_db"
  ssl_mode: "disable"

path_of_migration: "./goauthapp/repository/database/migrations"